export { default as AdminDashboard } from './AdminDashboard';
export { default as AdminUsers } from './AdminUsers';
export { default as AdminCourses } from './AdminCourses';
export { default as AdminClasses } from './AdminClasses';
export { default as AdminAssignments } from './AdminAssignments';
export { default as AdminDiscussions } from './AdminDiscussions';
export { default as AdminReports } from './AdminReports';
export { default as AdminSettings } from './AdminSettings';
export { default as AdminCreateUser } from './AdminCreateUser';
