export { default as StudentDashboard } from './StudentDashboard';
export { default as StudentCourses } from './StudentCourses';
export { default as StudentClasses } from './StudentClasses';
export { default as StudentAssignments } from './StudentAssignments';
export { default as StudentGrades } from './StudentGrades';
export { default as StudentSchedule } from './StudentSchedule';
export { default as StudentDiscussions } from './StudentDiscussions';
export { default as StudentHistory } from './StudentHistory';
export { default as StudentSettings } from './StudentSettings';
